// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGaa4u4kUPhz7o3Vj6g-SG7NkyGEsYZ3Y',
    appId: '1:835397356883:web:8a6a8d37bc24fb34d9e5a6',
    messagingSenderId: '835397356883',
    projectId: 'flutter--sign-in-816fb',
    authDomain: 'flutter--sign-in-816fb.firebaseapp.com',
    storageBucket: 'flutter--sign-in-816fb.appspot.com',
    measurementId: 'G-NYRZPT068P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7PvNtPzyMTu0o-oGPsTAcUtmkVIo5yEw',
    appId: '1:835397356883:android:e56772030909f28ed9e5a6',
    messagingSenderId: '835397356883',
    projectId: 'flutter--sign-in-816fb',
    storageBucket: 'flutter--sign-in-816fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCrdLTALGCLGdrHbK3P5MQKxk0Hg_T8nk',
    appId: '1:835397356883:ios:03022061d5d0aa0ed9e5a6',
    messagingSenderId: '835397356883',
    projectId: 'flutter--sign-in-816fb',
    storageBucket: 'flutter--sign-in-816fb.appspot.com',
    iosBundleId: 'com.example.googleAuthenticaticationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCrdLTALGCLGdrHbK3P5MQKxk0Hg_T8nk',
    appId: '1:835397356883:ios:08b6dc81fb0fc01ad9e5a6',
    messagingSenderId: '835397356883',
    projectId: 'flutter--sign-in-816fb',
    storageBucket: 'flutter--sign-in-816fb.appspot.com',
    iosBundleId: 'com.example.googleAuthenticaticationFirebase.RunnerTests',
  );
}
